Import NumPy and Store Battery Data

In [ ]:
import numpy as np

# Battery sensor data
battery_data = [
    [0, 32, 400, 20, 95],
    [1, 35, 395, 22, 88],
    [2, 38, 390, 25, 80],
    [3, 40, 385, 28, 70],
    [4, 42, 380, 30, 60],
    [5, 45, 375, 32, 48]
]

print("Battery Sensor Data")
print("-------------------")

for reading in battery_data:
    print("Time:", reading[0], "h",
          "| Temperature:", reading[1], "°C",
          "| Voltage:", reading[2], "V",
          "| Current:", reading[3], "A",
          "| Charge:", reading[4], "%")

Battery Sensor Data
-------------------
Time: 0 h | Temperature: 32 °C | Voltage: 400 V | Current: 20 A | Charge: 95 %
Time: 1 h | Temperature: 35 °C | Voltage: 395 V | Current: 22 A | Charge: 88 %
Time: 2 h | Temperature: 38 °C | Voltage: 390 V | Current: 25 A | Charge: 80 %
Time: 3 h | Temperature: 40 °C | Voltage: 385 V | Current: 28 A | Charge: 70 %
Time: 4 h | Temperature: 42 °C | Voltage: 380 V | Current: 30 A | Charge: 60 %
Time: 5 h | Temperature: 45 °C | Voltage: 375 V | Current: 32 A | Charge: 48 %


High Temperature Alert

In [ ]:
print("Temperature Status")
print("------------------")

for reading in battery_data:
    temperature = reading[1]

    if temperature > 40:
        print("Time:", reading[0], "h - High Temperature Alert")
    else:
        print("Time:", reading[0], "h - Temperature Normal")

Temperature Status
------------------
Time: 0 h - Temperature Normal
Time: 1 h - Temperature Normal
Time: 2 h - Temperature Normal
Time: 3 h - Temperature Normal
Time: 4 h - High Temperature Alert
Time: 5 h - High Temperature Alert


Low Battery Alert

In [ ]:
print("Battery Charge Status")
print("---------------------")

for reading in battery_data:
    charge = reading[4]

    if charge < 50:
        print("Time:", reading[0], "h - Low Battery Alert")
    else:
        print("Time:", reading[0], "h - Battery Charge Normal")

Battery Charge Status
---------------------
Time: 0 h - Battery Charge Normal
Time: 1 h - Battery Charge Normal
Time: 2 h - Battery Charge Normal
Time: 3 h - Battery Charge Normal
Time: 4 h - Battery Charge Normal
Time: 5 h - Low Battery Alert


Battery Status Function

In [ ]:
def battery_status(charge):
    if charge > 70:
        return "High"
    elif charge >= 50:
        return "Medium"
    else:
        return "Low"


print("Battery Status")
print("--------------")

for reading in battery_data:
    time = reading[0]
    charge = reading[4]

    print("Time:", time, "h | Charge:", charge, "% | Status:", battery_status(charge))

Battery Status
--------------
Time: 0 h | Charge: 95 % | Status: High
Time: 1 h | Charge: 88 % | Status: High
Time: 2 h | Charge: 80 % | Status: High
Time: 3 h | Charge: 70 % | Status: Medium
Time: 4 h | Charge: 60 % | Status: Medium
Time: 5 h | Charge: 48 % | Status: Low


Convert Data into NumPy Array

In [ ]:
D = np.array([
    [32, 400, 20, 95],
    [35, 395, 22, 88],
    [38, 390, 25, 80],
    [40, 385, 28, 70],
    [42, 380, 30, 60],
    [45, 375, 32, 48]
])

print("Battery Data Matrix:")
print(D)

Battery Data Matrix:
[[ 32 400  20  95]
 [ 35 395  22  88]
 [ 38 390  25  80]
 [ 40 385  28  70]
 [ 42 380  30  60]
 [ 45 375  32  48]]


Shape of the Array

In [ ]:
print("Shape of the array:", D.shape)
print("Number of rows:", D.shape[0])
print("Number of columns:", D.shape[1])

Shape of the array: (6, 4)
Number of rows: 6
Number of columns: 4


Average of Each Parameter

In [ ]:
average = np.mean(D, axis=0)

print("Average Temperature:", average[0], "°C")
print("Average Voltage:", average[1], "V")
print("Average Current:", average[2], "A")
print("Average Charge:", average[3], "%")

Average Temperature: 38.666666666666664 °C
Average Voltage: 387.5 V
Average Current: 26.166666666666668 A
Average Charge: 73.5 %


Maximum and Minimum Temperature

In [ ]:
max_temperature = np.max(D[:, 0])
min_temperature = np.min(D[:, 0])

print("Maximum Temperature:", max_temperature, "°C")
print("Minimum Temperature:", min_temperature, "°C")

Maximum Temperature: 45 °C
Minimum Temperature: 32 °C


Extract Voltage Column

In [ ]:
voltage = D[:, 1]

print("Voltage Column:")
print(voltage)

Voltage Column:
[400 395 390 385 380 375]


Identify High-Temperature Readings

In [ ]:
high_temperature = D[D[:, 0] > 40]

print("High-Temperature Readings:")
print(high_temperature)

High-Temperature Readings:
[[ 42 380  30  60]
 [ 45 375  32  48]]


Identify Low-Battery Readings

In [ ]:
low_battery = D[D[:, 3] < 50]

print("Low-Battery Readings:")
print(low_battery)

Low-Battery Readings:
[[ 45 375  32  48]]


Task 3 — Linear Algebra
Define Matrix A and Vector X

In [ ]:
A = np.array([
    [2, 1],
    [1, 3]
])

X = np.array([
    40,
    25
])

print("Matrix A:")
print(A)

print("\nVector X:")
print(X)

Matrix A:
[[2 1]
 [1 3]]

Vector X:
[40 25]


Calculate Y = AX

In [ ]:
Y = A @ X

print("Y = AX")
print("Y =", Y)

Y = AX
Y = [105 115]


Transpose of A

In [ ]:
A_transpose = A.T

print("Transpose of A:")
print(A_transpose)

Transpose of A:
[[2 1]
 [1 3]]


Determinant of A

In [ ]:
det_A = np.linalg.det(A)

print("Determinant of A:", det_A)

Determinant of A: 5.000000000000001


Inverse of A

In [ ]:
A_inverse = np.linalg.inv(A)

print("Inverse of A:")
print(A_inverse)

Inverse of A:
[[ 0.6 -0.2]
 [-0.2  0.4]]


Solve the System of Equations

In [ ]:
B = np.array([
    100,
    120
])

solution = np.linalg.solve(A, B)

x = solution[0]
y = solution[1]

print("Solution:")
print("x =", x)
print("y =", y)

Solution:
x = 36.0
y = 28.0


Verify the Solution

In [ ]:
print("Verification:")

print("2x + y =", 2*x + y)
print("x + 3y =", x + 3*y)

Verification:
2x + y = 100.0
x + 3y = 120.0


Task 4 — Calculus
Define Charge Function

In [ ]:
def charge_function(t):
    return 100 - 2*t - 0.5*t**2

print("Charge at t = 0:", charge_function(0), "%")
print("Charge at t = 2:", charge_function(2), "%")
print("Charge at t = 5:", charge_function(5), "%")

Charge at t = 0: 100.0 %
Charge at t = 2: 94.0 %
Charge at t = 5: 77.5 %


Derivative of Charge Function

In [ ]:
def discharge_rate(t):
    return -2 - t

print("dC/dt =", "-2 - t")

dC/dt = -2 - t


Discharge Rate at t = 2

In [ ]:
rate_at_2 = discharge_rate(2)

print("Discharge rate at t = 2 hours:", rate_at_2, "% per hour")

Discharge rate at t = 2 hours: -4 % per hour


Discharge Rate at t = 5

In [ ]:
rate_at_5 = discharge_rate(5)

print("Discharge rate at t = 5 hours:", rate_at_5, "% per hour")

Discharge rate at t = 5 hours: -7 % per hour


Calculus Interpretation

In [ ]:
if abs(rate_at_5) > abs(rate_at_2):
    print("The battery is losing charge at an increasing rate.")
elif abs(rate_at_5) == abs(rate_at_2):
    print("The battery is losing charge at a constant rate.")
else:
    print("The battery is losing charge at a decreasing rate.")

The battery is losing charge at an increasing rate.


Final Analysis
Find First High Temperature

In [ ]:
for reading in battery_data:
    time = reading[0]
    temperature = reading[1]

    if temperature > 40:
        print("Temperature first exceeds 40°C at:", time, "hours")
        break

Temperature first exceeds 40°C at: 4 hours


Calculate Total Charge Reduction

In [ ]:
initial_charge = battery_data[0][4]
final_charge = battery_data[-1][4]

charge_loss = initial_charge - final_charge

print("Initial Charge:", initial_charge, "%")
print("Final Charge:", final_charge, "%")
print("Total Charge Reduction:", charge_loss, "%")

Initial Charge: 95 %
Final Charge: 48 %
Total Charge Reduction: 47 %
